version: "2"
services:
 explorer:
   container_name: harvester-bluebottle
   image: jluisred/harvester-bluebottle
   external_links:
     - column-db
     - document-db
     - graph-db
     - event-bus
   networks:
     - "lnet"
networks:
  lnet:
    external:
      name: distribution_lnet
